---
title: "homework_06"
author: "linchenwang"
date: "2026-04-17"
output: word_document
---

1. 利用QGIS中quickmapservices和quickOSM插件，详细描述有关步骤，从OSM访问和下载doubs数据，通过选择特征获得准确的doubs，并保存为doubs_river.geojson格式。
 
    1.安装插件
      在 QGIS 的“插件管理器”中安装：
      QuickMapServices：用于加载 OSM 底图；
      QuickOSM：用于从 OpenStreetMap 下载矢量数据
      
    2. 加载底图
      通过 Web → QuickMapServices → OpenStreetMap 加载 OSM 底图；
      缩放到法国—瑞士交界附近，找到 Doubs 河所在区域；
      下载 OSM 河流数据；
      打开 QuickOSM
      
    3.设置查询条件：
      key = waterway；
      value = river；
      查询范围可设为当前地图窗口范围
      
    4.筛选准确的 Doubs 河流
      打开下载图层的属性表；
      用“按表达式选择”筛选："name" = 'Doubs'；
      结合底图核对，确保选中的是正确的 Doubs 主河道
      
    5.导出结果
      右键图层 → 导出 → 另存为；
      格式选择 GeoJSON；
      文件名设为：
      waterway_river_doubs.geojson
      勾选 仅保存所选要素 
    
2. 关于生物群落数据的探索性分析，主要包括针对样地/样点的分析（Q-mode），以及针对物种/栖息地环境的分析（R-mode），请回答如下问题：
1）针对样点的分析主要是聚类分析，聚类分析是基于距离、相关系数或协方差？ 有哪几种主要聚类方法？
    
    比较样点间的相似性或相异性，采用的聚类分析是基于计算距离的方法。其中包括：
      a)	欧几里得距离。在生态学分析中，可以使用它来处理地理因素、环境指标、生物性状等数据。
      b)	弦距离。首先对原始物种丰度数据执行范数标准化，又称为弦转化，再使用弦转化后的物种数据计算欧几里得距离，即为弦距离。
      c)	Hellinger距离。首先对原始物种丰度数据执行Hellinger转化，再使用转化后的物种数据计算欧几里得距离，即为Hellinger距离。
      d)	Bray-curtis距离。又称Bray-curtis相异度。

2）针对物种或环境的分析主要是排序分析，即识别物种按照特定的环境梯度变化的规律，排序是基于距离还是相关系数、协方差？如何选择排序模型（单峰或线性模型）？限制性排序与非限制性排序主要区别是什么？
    
    针对物种或环境的排序分析是基于相关系数/协方差。
    排序依据
    不同方法基础不同：
    PCA / RDA：偏向协方差、相关结构
    NMDS / PCoA：基于距离矩阵
    CA / CCA / DCA：适合群落生态数据
    
    线性模型还是单峰模型
    线性模型：物种对环境变化呈线性响应时使用
    如 PCA、RDA
    单峰模型：物种在某一环境条件下达到最适值时使用
    如 CA、CCA、DCA
    
    限制性排序与非限制性排序
    非限制性排序：只根据群落数据本身排序
    如 PCA、CA、DCA、NMDS
    限制性排序：排序轴受环境变量约束
    如 RDA、CCA
  
3）对双序图/三序图的解释要看标度，当scaling=1，该图表示的意思是什么？当scaling=2，图中矢量长度和夹角分别表示的是什么？

      scaling = 1
      主要解释样点之间的关系
      样点之间距离越近，群落组成越相似
      scaling = 2
      主要解释物种和环境变量之间的关系
      箭头长度：表示环境变量与排序轴关系强弱
      越长说明影响越大
      箭头夹角：
      小角度：正相关
      接近 90°：相关弱
      接近 180°：负相关

